defmodule Rezmq.Consts do
  @spec socket_type_to_id(atom()) :: integer()
  def socket_type_to_id(ty) do
    case ty do
      :pair -> 0
      :pub -> 1
      :sub -> 2
      :req -> 3
      :rep -> 4
      :dealer -> 5
      :router -> 6
      :pull -> 7
      :push -> 8
      :xpub -> 9
      :xsub -> 10
      :stream -> 11
    end
  end

  @spec option_name_to_id(atom()) :: integer()
  def option_name_to_id(name) do
    case name do
      :affinity -> 4
      :routing_id -> 5
      :subscribe -> 6
      :unsubscribe -> 7
      :rate -> 8
      :recovery_ivl -> 9
      :sndbuf -> 11
      :rcvbuf -> 12
      :rcvmore -> 13
      :fd -> 14
      :events -> 15
      :type -> 16
      :linger -> 17
      :reconnect_ivl -> 18
      :backlog -> 19
      :reconnect_ivl_max -> 21
      :maxmsgsize -> 22
      :sndhwm -> 23
      :rcvhwm -> 24
      :multicast_hops -> 25
      :rcvtimeo -> 27
      :sndtimeo -> 28
      :last_endpoint -> 32
      :router_mandatory -> 33
      :tcp_keepalive -> 34
      :tcp_keepalive_cnt -> 35
      :tcp_keepalive_idle -> 36
      :tcp_keepalive_intvl -> 37
      :immediate -> 39
      :xpub_verbose -> 40
      :router_raw -> 41
      :ipv6 -> 42
      :mechanism -> 43
      :plain_server -> 44
      :plain_username -> 45
      :plain_password -> 46
      :curve_server -> 47
      :curve_publickey -> 48
      :curve_secretkey -> 49
      :curve_serverkey -> 50
      :probe_router -> 51
      :req_correlate -> 52
      :req_relaxed -> 53
      :conflate -> 54
      :zap_domain -> 55
      :router_handover -> 56
      :tos -> 57
      :connect_routing_id -> 61
      :gssapi_server -> 62
      :gssapi_principal -> 63
      :gssapi_service_principal -> 64
      :gssapi_plaintext -> 65
      :handshake_ivl -> 66
      :socks_proxy -> 68
      :xpub_nodrop -> 69
      :blocky -> 70
      :xpub_manual -> 71
      :xpub_welcome_msg -> 72
      :stream_notify -> 73
      :invert_matching -> 74
      :heartbeat_ivl -> 75
      :heartbeat_ttl -> 76
      :heartbeat_timeout -> 77
      :xpub_verboser -> 78
      :connect_timeout -> 79
      :tcp_maxrt -> 80
      :thread_safe -> 81
      :multicast_maxtpdu -> 84
      :vmci_buffer_size -> 85
      :vmci_buffer_min_size -> 86
      :vmci_buffer_max_size -> 87
      :vmci_connect_timeout -> 88
      :use_fd -> 89
      :gssapi_principal_nametype -> 90
      :gssapi_service_principal_nametype -> 91
      :bindtodevice -> 92
    end
  end
end
